### ISSUE TITLE
Setting Debug to False removes access to static files

### ISSUE THREAD

**Issue by Demfier** [kaustubhhiware/c0derunR#7]
@kaustubhhiware Either we can use an older version of Django (I don't like the idea though) or we have to configure the server to handle it for us.

**Comment by kaustubhhiware** [comment]
I think this is resolved, @Demfier ?

**Comment by Demfier** [comment]
@kaustubhhiware No, it isn't resolved. We are still using `DEBUG=True` in our settings.
As I mentioned earlier, we have to configure our server to handle the static files for us.
Refer to this [link](https://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail) for more context of the error.

**Comment by 142ayushkumar** [comment]
@Demfier  `python manage.py runserver --insecure` and using Whitenoise ,both seems to be working

**Comment by 142ayushkumar** [comment]
Can you assign me this issue?

**Comment by 142ayushkumar** [comment]
Can you assign me this issue?

**Comment by 142ayushkumar** [comment]
@Demfier @kaustubhhiware
